# Generated by Django 2.2.dev20180601101617 on 2018-06-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
